### ISSUE TITLE
tableView重复叠加问题

### ISSUE THREAD

**Issue by ElvistLui** [liuzhiyi1992/ZYSideSlipFilter#1]
我在ZYSideSlipFilterController.m的-(void)show;方法中打印页面上tableView的数量，发现点击击多少次“筛选”按钮，页面就会有多少个相同的tableView叠加在一起。在- (void)configureUI;方法里对_mainTableView做判空处理，就可以解决。

**Comment by liuzhiyi1992** [comment]
朋友观察得很仔细，这是个严重的bug，已处理
